# Generated by Django 3.1.4 on 2021-02-18 23:28

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210218_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=False, null=True, quality=100, size=[720, 576], upload_to='dashboard/images/'),
        ),
    ]
