# Generated by Django 3.1.4 on 2021-02-22 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210218_2328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
