# Generated by Django 3.1.4 on 2021-02-22 18:07

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=False, null=True, quality=100, size=[720, 576], upload_to='dashboard/images/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
